### ISSUE TITLE
First impression and some small issues

### ISSUE THREAD

**Issue by MarkusVolk** [nwg-piotr/nwg-look#1]
First of all, I would like to thank you for your tireless efforts. I use nwg-shell components in yocto/openembedded build environment and I am really thankful for that tools that enrich wlroots/sway a lot.

Found two small issues:

https://github.com/nwg-piotr/nwg-look/blob/05b482a052cceb0f8ce9b7550632c35d4708d4f8/stuff/nwg-look.desktop#L11
I guess we would need to remove .svg from this line

And if wearing the distributors hat, i'd like to have a LICENSE file to ship with the package

Apart from this i did succeed in building nwg-look for x86-64 and aarch64.

Looks awesome. Great work!

**Comment by nwg-piotr** [comment]
Thank you very much for feedback! Fixed.
