### ISSUE TITLE
Default font menu has overlapping text

### ISSUE THREAD

**Issue by Coalemus** [nwg-piotr/nwg-look#11]
![image](https://user-images.githubusercontent.com/61069122/162623244-2dfdc429-3023-4f9b-a61c-9230b478e34e.png)

This part specifically
![image](https://user-images.githubusercontent.com/61069122/162623284-3f86901e-a39d-4d4a-8593-7f826efa0912.png)

System Specs are:

OS: Arch Linux x86_64
WM: sway

**Comment by nwg-piotr** [comment]
LOL, strange that it didn't show up on my machine. Fixing now, thanks.

**Comment by nwg-piotr** [comment]
Resolved by the way in #12
