### ISSUE TITLE
Desire

### ISSUE THREAD

**Issue by Ved-un** [nwg-piotr/nwg-look#15]
I thought it was a good app, but it turned out to be a copy of LXappearance, with the same disease, so I deleted it...

The question is - why are you violating the XDG specification?
Why are you polluting the HOME catalog?

Themes and icons should be here
~/.local/share/icons
~/.local/share/themes 

and gtk files should be here
~/.config/gtk-2.0/gtkrc
~/.config/gtk-3.0/settings.ini

**Comment by nwg-piotr** [comment]
> Themes and icons should be here
~/.local/share/icons
~/.local/share/themes

That's you business, and has nothing to do with the program.

> and gtk files should be here
~/.config/gtk-2.0/gtkrc
~/.config/gtk-3.0/settings.ini

Read Wiki before posting: https://wiki.archlinux.org/title/GTK#Configuration
