### ISSUE TITLE
Settings are reset after restarting Sway config or reboot

### ISSUE THREAD

**Issue by Sunderland93** [nwg-piotr/nwg-look#16]
All theme settings are correctly applied, but after restarting Sway config all reset to default Adwaita theme. The only workaround for this is using import-gsettings script https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland

nwg-look 0.1.3
Ubuntu 22.04 LTS
Sway 1.7

**Comment by nwg-piotr** [comment]
I'd say something in your system must revert them. No idea, I haven't used Ubuntu for years, and also I haven't seen your configs. Could you paste your sway config file?

**Comment by nwg-piotr** [comment]
Closing due to no further feedback.

**Comment by jahway603** [comment]
I'm having this same issue as OP, but 3 years after the reported it. This issue remains unresolved, and I do not have permission to re-open this issue, so can you please re-open this to explore a solution @nwg-piotr ? Thank you.

nwg-look 1.0.6
Artix Linux
Sway 1.11

**Comment by jahway603** [comment]
@Sunderland93 thank you for your response. It's fixed now.
