### ISSUE TITLE
gtk-4 support

### ISSUE THREAD

**Issue by roland-5** [nwg-piotr/nwg-look#22]
It would be awesome if nwg-look could handle gtk-4.

**Comment by Lazerbeak12345** [comment]
libadwaita support might be needed for this to work (granted, reddit says that libadwaita is quite easy to work around)

**Comment by nwg-piotr** [comment]
Arch Wiki:

> Note: For libadwaita-based GTK 4 applications, the chosen GTK theme needs [special support](https://github.com/jnsh/arc-theme/issues/61#issuecomment-922380704) and you are required to force a GTK theme with the GTK_THEME [environment variable](https://wiki.archlinux.org/title/Environment_variable), or use a patched version of libadwaita: [libadwaita-without-adwaita-git](https://aur.archlinux.org/packages/libadwaita-without-adwaita-git/)AUR.

To launch apps with `GTK_THEME=<theme_name> <command>`, you may use nwg-drawer with the `-ft` (force theme) argument. It will check `gsettings get org.gnome.desktop.interface gtk-theme` and use the value as the theme name.

It's quite easy to use with nwg-shell:

![obraz](https://github.com/nwg-piotr/nwg-look/assets/20579136/b531bcc1-fbce-4ce7-b0a1-d1c322639939)

**Comment by Lazerbeak12345** [comment]
Libadwaita aside, does this issue closure mean it works with gtk4 now?

**Comment by Lazerbeak12345** [comment]
I appreciate your engagement.

Isn't that workaround only needed for libadwaita? Inkscape, for example, has plans to eventually move to gtk4 - but will not be using libadwaita. This would mean gtk4 support will still be needed. From my research it's more or less identical to gtk3, but supporting gtk4 will _not_ automatically work on the unwisely backwards incompatible libadwaita.

I'm not pushing for libadwaita support. Just gtk4.

**Comment by nwg-piotr** [comment]
Well, I don't use gnome, and only have gnome-calculator installed for testing. This would need further investigation.

**Comment by Lazerbeak12345** [comment]
From my testing, nearly all gnome apps are libadwaita. I don't yet know of a good example of an app that is gtk4, but is not libadwaita.

**Comment by nwg-piotr** [comment]
Let me know when you find one, please.

**Comment by Lazerbeak12345** [comment]
The arch Linux package `gtk4-demos` includes a few - note that these are _not_ "real-world" applications, but do seem to be great for testing theming tools like this one.

**Comment by Lazerbeak12345** [comment]
`transmission-gtk` is a real one

**Comment by Lazerbeak12345** [comment]
`vte4` is gtk4 only

**Comment by nwg-piotr** [comment]
> `vte4` is gtk4 only

And it seems to work perfectly well with nwg-look.

**Comment by Lazerbeak12345** [comment]
perfect! gtk4 must check the gtk3 settings, and just magically work! I hadn't had the time to test this myself!
