### ISSUE TITLE
Feature request: make it a a standalone app

### ISSUE THREAD

**Issue by paulodiovani** [nwg-piotr/nwg-look#23]
The new settings and welcome even for those who are not using nwg-shell. It would be great to be able to install it as a standalone application. instead of `lxappearence`.

**Comment by nwg-piotr** [comment]
LOL, what stops you from doing so? I know some people who use nwg-look with X11.

**Comment by paulodiovani** [comment]
I must have been tired yesterday, I don't know how I missed this is AUR. :facepalm: 

```
aur/nwg-look 0.1.4-1 (+6 1.45)
    GTK3 settings editor adapted to work in sway/wlroots environment
aur/nwg-look-bin 0.1.4-1 (+7 1.34)
    GTK3 settings editor adapted to work in the sway/wlroots environment (binary package)
```

Thanks for the answer. I'm closing the issue.

BTW, awesome project!

**Comment by nwg-piotr** [comment]
Thank you!
