### ISSUE TITLE
Build Error in Arch, using Paru to install nwg-look-git

### ISSUE THREAD

**Issue by dedguy21** [nwg-piotr/nwg-look#28]
using arch, I get the following error when paru tries to install:
# github.com/gotk3/gotk3/glib
cgo-gcc-prolog: In function ‘_cgo_200740c87a77_Cfunc_g_binding_get_source’:
cgo-gcc-prolog:71:2: warning: ‘g_binding_get_source’ is deprecated: Use 'g_binding_dup_source' instead [-Wdeprecated-declarations]
In file included from /usr/include/glib-2.0/glib-object.h:24,
                 from /usr/include/glib-2.0/gio/gioenums.h:30,
                 from /usr/include/glib-2.0/gio/giotypes.h:30,
                 from /usr/include/glib-2.0/gio/gio.h:28,
                 from ../go/pkg/mod/github.com/gotk3/gotk3@v0.6.1/glib/gbinding.go:3:
/usr/include/glib-2.0/gobject/gbinding.h:115:23: note: declared here
  115 | GObject *             g_binding_get_source          (GBinding *binding);
      |                       ^~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: In function ‘_cgo_200740c87a77_Cfunc_g_binding_get_target’:
cgo-gcc-prolog:107:2: warning: ‘g_binding_get_target’ is deprecated: Use 'g_binding_dup_target' instead [-Wdeprecated-declarations]
/usr/include/glib-2.0/gobject/gbinding.h:119:23: note: declared here
  119 | GObject *             g_binding_get_target          (GBinding *binding);
      |                       ^~~~~~~~~~~~~~~~~~~~

**Comment by nwg-piotr** [comment]
> to install nwg-look-git

Ain't no such package.

The gotk3 library needs a lot of time (even up to 20 - 30 minutes) to build, and gives no sign of life in the meantime. What you pasted are gotk3 build warnings, meaningless to us.

You need to either be more patient, or install the pre-compiled nwg-look-bin package (recommended).

**Comment by dedguy21** [comment]
Thank you 👍
