### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by theshatterstone** [nwg-piotr/nwg-look#30]
Do you have any plans on getting nwg-look packaged on NixOS? Thanks.

**Comment by theshatterstone** [comment]
No problem. I was just wondering about it. Thanks for your fast response!

**Comment by nwg-piotr** [comment]
Some [nwg-shell](https://github.com/nwg-piotr/nwg-shell) components have already been packaged for NixOS (see Repology badges). Maybe you could identify packager(s)?
