### ISSUE TITLE
Changing cursor changes icons, unable to change icons back afterwards

### ISSUE THREAD

**Issue by David-Aguilo** [nwg-piotr/nwg-look#31]
Greetings. First of all, I'd like to thank you for this very useful software.

I am using nwg-look to change the look of gtk on hyprland. I was using breeze-dark icons and cursor, when I decided to change the cursor to Catppuccin-Mocha-Dark from the AUR. In selecting a different cursor, all icons changed to adwaita (i noticed this on thunar, which is the main gtk program i use), and all my attempts to set a different icon set were for naught, as I seem to be unable to change the icons using nwg-look. I have had to install kde-plasma and make the change there in order to be able to have my old icons with the new cursor.

I'm attaching a video showcasing the issue as well as a log file of the output of nwg-look.

https://user-images.githubusercontent.com/89081503/233036291-57f6e182-517c-4030-9a31-bb4c7fc85274.mp4

[nwg-look.log](https://github.com/nwg-piotr/nwg-look/files/11271541/nwg-look.log)

**Comment by nwg-piotr** [comment]
I've just installed the `catppuccin-mocha-dark-cursors` AUR package. Everything works well on my side, and changing the cursor theme does not affect the icon theme. This must be something about your environment. I noticed you use some exotic keys in `/home/david/.config/gtk-3.0/settings.ini`. Do you use a script to apply these settings? Possibly it overwrites what nwg-look applies directly. No better idea at the moment.

**Comment by nwg-piotr** [comment]
Can't reproduce it on my side. Does it happen on sway as well? May I see your hyprland.conf?

**Comment by nwg-piotr** [comment]
Also: maybe something is wrong with you breeze icon theme? I couldn't install any, always ended up in errors.

**Comment by David-Aguilo** [comment]
I have installed another icon theme to see if I had better luck, and I could not apply that one either, so it doesn't seem like the breeze icon theme is at fault. I have also tried using a laptop that has never had kde installed onto it, only hyprland. And the issue also happens on it, so it doesn't seem like it was kde's fault either. I'll try to setup sway and test, in the meantime, here is my hyprland.conf.

[hyprland.conf.txt](https://github.com/nwg-piotr/nwg-look/files/11273890/hyprland.conf.txt)

**Comment by nwg-piotr** [comment]
Still no clue. It will be very difficult to diagnose.

**Comment by David-Aguilo** [comment]
I have installed sway on the laptop and the results are the same, I cannot change the icon theme either. If I can provide more information, please ask.

**Comment by nwg-piotr** [comment]
I can only shoot blindly. Below you see dependencies of [nwg-shell](https://nwg-piotr.github.io/nwg-shell), which nwg-look was written for. You could randomly try installing GTK-related stuff out of them, which is currently missing from your system. I would start from `gnome-themes-extra`.

```text
depends=('foot' 'gnome-themes-extra' 'grim' 'imagemagick' 'jq'
         'libappindicator-gtk3' 'light' 'ttf-dejavu'
         'network-manager-applet' 'pacman-contrib' 
         'papirus-icon-theme' 'playerctl' 'polkit-gnome' 
         'python-geopy' 'python-yaml' 'slurp' 'swappy' 'sway' 'swayidle'
         'swaylock' 'swaybg' 'wl-clipboard' 'xorg-xwayland' 'wlsunset' 
         'azote' 'gopsuinfo' 'nwg-bar-bin' 'nwg-dock-bin' 'nwg-drawer-bin' 
         'nwg-menu-bin' 'nwg-look-bin' 'nwg-panel' 'nwg-shell-config' 
         'nwg-shell-wallpapers' 'nwg-displays' 'python-dasbus' 'swaync' 'gtklock'
         'gtklock-userinfo-module' 'gtklock-powerbar-module' 'gtklock-playerctl-module')
```

**Comment by nwg-piotr** [comment]
One more thing: are you on GTK3? Nwg-look does not support GTK4.

**Comment by David-Aguilo** [comment]
I am using gtk3, it's the only gtk I currently have installed. Weirdly enough it may end up being the breeze icon theme, I guess the other one I downloaded to test presents the same issue, because now I have downloaded gnome-themes-extra as per your recommendation, which has added the HighContrast icon theme, which I can set without issue. I have also tried with the pop os icon theme and it also works. It's only when trying to set breeze that adwaita is set (I guess because it is the default).

**Comment by nwg-piotr** [comment]
> Weirdly enough it may end up being the breeze icon theme

I do hope so. The latest release had almost 3500 downloads since March, 7th. Someone would've reported earlier, if it was a common issue.

**Comment by David-Aguilo** [comment]
Good morning.

After doing further testing I have realised something that all themes that work have in common, and it is the fact that their name is a single word, while all themes that don't work have a space in their name.

Both pop OS' theme and HighContrast theme (which work), are a single word which is written into `.config/gtk-3.0/settings.ini` in the following manner:

`gtk-icon-theme-name=Pop`
`gtk-icon-theme-name=HighContrast`

While breeze dark and tela black, which do not work, are written into settings.ini in the following manner:

`gtk-icon-theme-name=Breeze Dark`
`gtk-icon-theme-name=Tela black`

I have tested to see how the plasma settings deal with this, since setting the icon using that works, the setting for Tela dark and breeze dark are set by the plasma settings in the following manner:

`gtk-icon-theme-name=Tela-black`
`gtk-icon-theme-name=breeze-dark`

This being the cause of the problem is further corroborated by the fact that base Tela (which is also only one word), is the only Tela theme that works.

**Comment by David-Aguilo** [comment]
Thank you for the software and for being so responsive. Good luck in finding a solution.

**Comment by nwg-piotr** [comment]
Sorry for making you wait that long. I was busy on another project and forgot about this problem a bit. I think I found a fix.

**Comment by David-Aguilo** [comment]
Hey. Sorry I didn't see your reply before. No worries man, thank you for fixing the problem.

**Comment by nwg-piotr** [comment]
Thanks for reporting. This was quite a serious bug.
