### ISSUE TITLE
Cursors not showing up.

### ISSUE THREAD

**Issue by RoccoRakete** [nwg-piotr/nwg-look#38]
they are located in ~/.icons

**Comment by nwg-piotr** [comment]
Well, what can I say? It works for me, and none of over 10 thousand users complained yet.

![image](https://github.com/nwg-piotr/nwg-look/assets/20579136/61ecedb7-0a9f-4269-ab6b-7e6e827825e8)

I know nothing about your system, even what your distro is, so I can't help.
