### ISSUE TITLE
the cursor size function not working 

### ISSUE THREAD

**Issue by NotWinder** [nwg-piotr/nwg-look#39]
hi when i set a size for the cursor it dosen't apply it.(it only applys it for google chrome)
i did get it working by setting the cursor in .Xresources 
but i wanted to inform you with this problem

i'm using dwm on debian 12

**Comment by sawb** [comment]
Same here, but I don't see the setting taking effect anywhere.
I'm on Wayland, so not sure if I can change it in Xresources as you did. 

Using Hyprland on Arch here.

**Comment by nwg-piotr** [comment]
This is a GTK settings editor, not a part of Hyprland ecosystem. Over GTK windows the cursor size changes, provided that you don't override it in env variables. The rest is out of my range.
