### ISSUE TITLE
Now my gnome apps use different colors

### ISSUE THREAD

**Issue by HarHarLinks** [nwg-piotr/nwg-look#4]
Hello, I tried this out on arch linux, sway 1.7 with a couple gnome apps.

I used Adapta before and used nwg-look to try and switch to Adwaita and/or Adwaita-dark:
![image](https://user-images.githubusercontent.com/2803622/162470795-ea89a756-f514-4b9b-82ff-1aabcc228980.png)

At first it seemed to work: easyeffects and the keyring unlock dialogue both now use the theme as shown by nwg-look's preview.
But then I noticed that galculator and evince use a light theme version instead:
![image](https://user-images.githubusercontent.com/2803622/162471215-34a4f8b5-c081-430b-9aec-b3649833ddea.png)

Am I doing something wrong?

**Comment by ErikReider** [comment]
It's the move to Gtk4... Try this `gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"`
The value can be `default`, `prefer-dark` or `prefer-light`. @nwg-piotr you should probably add this as a setting :)

**Comment by nwg-piotr** [comment]
Good point, @ErikReider. I will, thank you.

**Comment by nwg-piotr** [comment]
![2022-04-09-012217_screenshot](https://user-images.githubusercontent.com/20579136/162545865-b0e94f47-70eb-419d-b837-51ade9ebb4d5.png)

**Comment by HarHarLinks** [comment]
@nwg-piotr Thanks for addressing this so quickly!
I had trouble finding the new dropdown selection boxes at first glance, since my mind grouped them into the preview automatically. Perhaps moving them to the left side would be appropriate if left is setting and right is preview, or on top of the preview so you can't mistake anything after the preview as belonging to the preview?

**Comment by nwg-piotr** [comment]
For the sake of code simplicity I'd rather leave it as is.
