### ISSUE TITLE
Nixpkg? [Feature Request]

### ISSUE THREAD

**Issue by h4rldev** [nwg-piotr/nwg-look#43]
I want to change my Hyprland cursor and was redirected to this repo. There seems to not be any nixpkg of this, so I'm making an issue for it

**Comment by nwg-piotr** [comment]
Sorry, but I only do packaging for AUR. Please ask the NixOS community for the package.

**Comment by nwg-piotr** [comment]
Of course. Let me know in case some action is required in my side.
