### ISSUE TITLE
Config Versioning Possibilities [Feature Request]

### ISSUE THREAD

**Issue by Natr1x** [nwg-piotr/nwg-look#44]
I like to keep track of my config files with git so I would like to know what files `nwg-look` stores configurations in / is dependant on. Git is also not great at handling binary files so if possible I would like to exclude such files from being versioned (such as dconf files).

## What I'm Requesting:

- Documentation for what files need to be versioned in order to be able to restore settings to a similar state with said files. I e I would like to be able to use git to restore my settings after for example a reinstallation.
- If the above mentioned files include binary files (such as dconf files) then I would ideally want a way to export/import those configs in a more human readable and git friendlier text format. But if that functionality is out of scope or hard to implement then I am would be very happy to just have documentation for which settings are stored in that way. That way users can determine for themselves if they want to save save those settings.

**Comment by nwg-piotr** [comment]
Those are just 2 simple files:

1.`~/.config/nwg-look/config` (json), that stores program settings; default values:

```json
{
 "export-settings-ini": true,
 "export-gtkrc-20": true,
 "export-index-theme": true,
 "export-xsettingsd": true
}
```

2.`~/.local/share/nwg-look/`, that stores latest settings in the format ready to export (`nwg-look -a`):

My current settings:

```text
# Generated by nwg-look, do not edit this file.
gtk-theme=Otis
icon-theme=Papirus-Dark
font-name=Cantarell 10
cursor-theme=Adwaita
cursor-size=24
toolbar-style=both-horiz
toolbar-icons-size=large
font-hinting=medium
font-antialiasing=grayscale
font-rgba-order=rgb
text-scaling-factor=1.0
color-scheme=default
event-sounds=true
input-feedback-sounds=false
```

**Comment by Natr1x** [comment]
Thank you, I figured it would be simple but you never know and I could not find any definitive documentation about it. This is enough for me. I admit I mostly created the issue more as a way to publicly ask the question than as a request for a feature I thought was missing.

**Comment by nwg-piotr** [comment]
Well, it's always not enough time to write docs. Feel free to contribute, if you can.
