### ISSUE TITLE
~/.icons/default folder should get created if it does not exist

### ISSUE THREAD

**Issue by simonfogliato** [nwg-piotr/nwg-look#45]
If you set a custom cursor theme without that folder, index.theme will never be created and the settings are not properly applied. For any updated setting file nwg-look should create the folder if it does not exist.

~/.icons/default/index.theme

Workaround:

mkdir -p ~/.icons/default

**Comment by nwg-piotr** [comment]
Thanks. I'll take a look at this.

**Comment by nwg-piotr** [comment]
This is already done here: https://github.com/nwg-piotr/nwg-look/blob/f0f9f7278d7cbaa85862ad9a0ab42886c5938d61/tools.go#L858

**Comment by simonfogliato** [comment]
I just did another quick test...

1. cd ~
2. mv .icons .icons_test
3. Open nwg_look and select any new valid mouse cursor
4. Click apply on the gui
5. ls -la
6. The .icons folder does not exist... The .icons folder does not get created...

If it helps the following is my entire setup: https://github.com/simonfogliato/dotfiles/blob/main/executable_arch.sh

pacman -Qm nwg-look
nwg-look 0.2.4-1

**Comment by simonfogliato** [comment]
I did a quick search and when I move the folder "mv .icons .icons_test" and apply a new cursor it will update the following file:

/home/sfogliato/.local/share/icons/default/index.theme

So it would seem to write in a different location.

**Comment by nwg-piotr** [comment]
The program looks for the `icons` folder in:

- `~/.icons`
- `$XDG_DATA_HOME/icons`
- `~/.local/share/icons`

in this certain order. The first location found will be used in further code execution. In case we find none of above, you'll see the `Couldn't find icons folder` warning in the command output. Run in terminal to check.

**Comment by simonfogliato** [comment]
That's it! Thanks for clearing this up.
