### ISSUE TITLE
make build stuck

### ISSUE THREAD

**Issue by viniasbr** [nwg-piotr/nwg-look#47]
Hello! When I run make build inside the cloned repository, the process gets stuck in `github.com/gotk3/gotk3/gtk`, and doesn't proceed. I initially tried it with makepkg from the AUR, and when I encountered this error, I tried to build from source by cloning the repository and building it. Both of the attempts resulted in the same thing.

**Comment by viniasbr** [comment]
Fixed! It seems it was on my side. Sorry for the unnecessary issue!

**Comment by Darkmoon1212** [comment]
> Fixed! It seems it was on my side. Sorry for the unnecessary issue!

Ran into the same error. How did you solve it?

**Comment by nwg-piotr** [comment]
> Ran into the same error. How did you solve it?

Building the gotk3 library takes time, and you may see no progress. It's over 10 minutes on my main machine, and up to 30 on my old testing lappy.

**Comment by Darkmoon1212** [comment]
> Building the gotk3 library takes time, and you may see no progress. It's over 10 minutes on my main machine, and up to 30 on my old testing lappy.

That did it. Thank you!
