### ISSUE TITLE
Command-line option to export nwg-look preferences to files

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/nwg-look#49]
> (...) is it possible to have a command-line option to export nwg-look preferences to files? i use nwg-look to set my themes, and on top of that, i have darkman for automatic dark mode toggling. i set my theme to a light one during the day, and a dark one when it's night time, and apps under XWayland reads the gtk settings files instead of directly reading from gsettings, so having a command-line option for nwg-look to automatically export to files would be really neat!

_Originally posted by @j1nxie in https://github.com/nwg-piotr/nwg-shell/discussions/157#discussioncomment-7571996_

**Comment by nwg-piotr** [comment]
I'll take a closer look at this soon.

**Comment by nwg-piotr** [comment]
@j1nxie - could you build from the `add-49` branch and tell me if it works for you? I've added the `-x` argument to read settings, export config files and quit. Only files marked in the Preferences tab will be exported.

**Comment by j1nxie** [comment]
> @j1nxie - could you build from the `add-49` branch and tell me if it works for you? I've added the `-x` argument to read settings, export config files and quit. Only files marked in the Preferences tab will be exported.

looks like it's working fine for me! built it from the branch and executed and everything ran smoothly without a hitch.

**Comment by nwg-piotr** [comment]
Does the execution with the -x argument resolve you issue? The light/dark theme switch is a kind of exception, as there are two different registry keys responsible for it.

**Comment by j1nxie** [comment]
i have a script that sets my gsettings registry keys for me, and this command-line switch looks just perfect to finish off what i need. thank you!

**Comment by nwg-piotr** [comment]
Thanks! I'll merge the branch, if so.
