### ISSUE TITLE
Config file location should be in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by murlakatamenka** [nwg-piotr/nwg-look#5]
At least I think so and where vast majority user configs are, not in `$XDG_DATA_HOME` (`~/.local/share`)

Summary: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

**Comment by nwg-piotr** [comment]
It's not a config file, but a data file, not expected to be edited by the user. If we need a config file in further development (probably we will), it will go the config home.

**Comment by LukasDoesDev** [comment]
https://wiki.archlinux.org/title/XDG_Base_Directory
Could you at least support the `GTK_RC_FILES` and `GTK2_RC_FILES` environment variables?
