### ISSUE TITLE
Fedora Copr for all your projects

### ISSUE THREAD

**Issue by JaKooLit** [nwg-piotr/nwg-look#51]
Hey bro, first off, I love your projects. 

I use mostly your nwg-look which is wayyyy better than any other gtk-settings / theming app in my opinion.

Question:

Do you have any plans on maintaining a COPR repo for our fedora users? 

Building from source is kinda takes long tbh and would be nice if there is for Fedora

(oh and maybe Debian) :)

TIA

**Comment by nwg-piotr** [comment]
Hi @JaKooLit!

Sorry but I know nothing on Fedora. I only maintain Arch (AUR) packages. The person you need is talk to is @t0fik.

**Comment by JaKooLit** [comment]
cool thanks alot for the quick reply and being honest...
