### ISSUE TITLE
Icon theme not being recognized.

### ISSUE THREAD

**Issue by BluewyDiamond** [nwg-piotr/nwg-look#54]
My icon theme is symlinked from one location to `~/.local/share/icons`, but it fails to be recognized. If I manually copy it to `~/.local/share/icons`, it functions correctly. However, I have specific reasons for preferring to use a symlink. Are there any solutions to this issue?

**Comment by nwg-piotr** [comment]
Sorry, we use the `os.path.exists()` function, that does not follow symlinks.
