### ISSUE TITLE
nwg-look with KDE plasma 6

### ISSUE THREAD

**Issue by Cherkah** [nwg-piotr/nwg-look#55]
i 've installed the pkg so as to correct font issues with some gtk apps on  endeavourOS (arch + plasma6) .
It does the job pretty well, but:
1) Why to block the app to create Desktop entry on the user desktop for GNOME;XFCE;MATE;KDE ?
2) in the console i get:
```
WARN[0000] Unsupported config key: gtk-decoration-layout 
WARN[0000] Unsupported config key: gtk-enable-animations 
WARN[0000] Unsupported config key: gtk-modules          
WARN[0000] Unsupported config key: gtk-primary-button-warps-slider 
WARN[0000] Unsupported config key: gtk-sound-theme-name 
WARN[0000] Unsupported config key: gtk-xft-dpi 
...
WARN[0018] Couldn't find icons folder ```

3) can you limit the production of GTK config files base on the default path of the major distros



Operating System: EndeavourOS 
KDE Plasma Version: 6.0.3
Graphics Platform: Wayland

**Comment by nwg-piotr** [comment]
> 1. Why to block the app to create Desktop entry on the user desktop for GNOME;XFCE;MATE;KDE ?

Could be discussed, but the program is aimed strictly at wlroots-based compositors.

> in the console i get: (...)

The only keys that should exist in the `~/.config/nwg-look/config` file are:

```json
{
 "export-settings-ini": <bool>,
 "export-gtkrc-20": <bool>,
 "export-index-theme": <bool>,
 "export-xsettingsd": <bool>
}
```

If you have something else in there, it's your mistake.

> 3) can you limit the production of GTK config files base on the default path of the major distros

No idea what you mean. See the "Preferences' tab.

![obraz](https://github.com/nwg-piotr/nwg-look/assets/20579136/2f0a5bd4-bda2-478b-8b39-784458cba5ac)

**Comment by Cherkah** [comment]
ok thanks
> the program is aimed strictly at wlroots-based compositors

i'm using plasma 6 with wayland and have no issue to use it

> The only keys that should exist in the ~/.config/nwg-look/config

Do not forget to includ those deprecated && LXAppearance compatibility (README).
that is why i have those warnings

> No idea what you mean

my bad, you're right. I saw it after sent  my post

regards
