### ISSUE TITLE
Change GTK settings via command line

### ISSUE THREAD

**Issue by TomyOne** [nwg-piotr/nwg-look#58]
Hello is there or in plan to have possibility to change setting directly from command line? 

Could be useful to quickly change let's say GTK theme between light and dark theme via keybinding.

Something like:
`nwg-look -c gtk-theme="theme-name"`

Thank you!

**Comment by TomyOne** [comment]
Well after checking the code I found out this solution for it, but a bit of hacking :) 

```
sed -i -e 's/gtk-theme=.*/gtk-theme=<THEME_NAME>/g' ${HOME}/.local/share/nwg-look/gsettings
nwg-look -a
```

**Comment by nwg-piotr** [comment]
Try `gsettings set org.gnome.desktop.interface gtk-theme "ThemeNameHere"`.

**Comment by TomyOne** [comment]
ahh yeah or that is much better :) Thanks!
