### ISSUE TITLE
xsettings support

### ISSUE THREAD

**Issue by elcste** [nwg-piotr/nwg-look#6]
I'd like to suggest `xsettings` support using **[xsettingsd](https://github.com/derat/xsettingsd)**, since some xwayland apps I've found, mostly using electron apps, only seem to follow some settings from xsettings. xsettingsd by default uses `.xsettingsd`. More info about configuring it on their wiki: https://github.com/derat/xsettingsd/wiki/Settings

There is also GNOME's xsettings daemon **`gsd-xsettings`**, but I haven't tried it and don't know how it works.

**Comment by nwg-piotr** [comment]
Added to TODO. Thank you.

> There is also GNOME's xsettings daemon

I don't care much if my stuff works in GNOME. They have own developers. :)

**Comment by elcste** [comment]
> I don't care much if my stuff works in GNOME. They have own developers. :)

I only mentioned it because I've read you can run it manually outside of GNOME, like with Sway. But of course they don't support it, and who knows if it will keep working. So xsettingsd still seems the best target.

**Comment by nwg-piotr** [comment]
Sure. I'll take a closer look at it later. For now I'll focus on `xsettingsd` and 2 other issues worth of attention.

**Comment by nwg-piotr** [comment]
Please check if it works for you. I see no special difference, as my Electron apps seemed to respect GTK settings without it.

**Comment by elcste** [comment]
> Please check if it works for you.

Will do, but might be a couple days, as my Sway machine is at work but I'm busy Monday.

**Comment by nwg-piotr** [comment]
NP. I'm going to release all the stuff tonight. If something doesn't work, just let me know.

**Comment by elcste** [comment]
I got some time, and my testing shows that while I thought I needed xsettingsd to get these apps to follow the settings, I really just needed to log out and log back in 😁  

Thanks for your work in any case. I don't see anywhere to buy you a coffee or beer, so I just donated to a Ukrainian refugee charity.

**Comment by nwg-piotr** [comment]
Haha! Beer helps much at coding stuff, but Polish tax regulations are so complicated that it is better not to deal with them. Thank you for helping the refugees!

Exporting xsettingsd may be useful under X11 session. I'll never know, as I use it hardly ever. ;)
