### ISSUE TITLE
nwg-look UI doesn't keep the custom settings

### ISSUE THREAD

**Issue by wastlnd** [nwg-piotr/nwg-look#61]
I am running labwc as Wayland compositor on Arch Linux. When I change the fonts, icons, mouse etc. and apply the application shows the correct preview but when I open it again I see the default settings again. Oddly, the gtk3 settings.ini file show the changes instead.

**Comment by nwg-piotr** [comment]
I've never used labwc, but those are GTK3 setting, that should be compositor-independent. I bet you have something else in your system that applies old settings back.

**Comment by wastlnd** [comment]
Yes, it's the first thing I have been thinking about. However, what perplex me is that gtkrc-2.0 and settings.ini do show my changes, it's just the GUI that still doesn't update. For example I have set the fonts to Liberation but when I open nwg-look it shows Cantatell.

**Comment by nwg-piotr** [comment]
Well, possibly it has something to do with labwc. Openbox had its own theming system, if I remember well.

**Comment by wastlnd** [comment]
Yes, It may be, I tried to inspect the env configuration file to search for particular exported variables bit the only one I found was about the cursor. There's something else that could potentially help, maybe. I found out that clicking the icon in the taskbar opens the app with a greyed out UI and the font quick search bar not clickable. If I run the app from terminal it opens fine.

**Comment by wastlnd** [comment]
I fixed the issues by running the app with `dbus-launch` (my dconf folder was missing).
