### ISSUE TITLE
nwg-look does not recognize custom cursors

### ISSUE THREAD

**Issue by FosRexx** [nwg-piotr/nwg-look#69]
So I have this custom cursors theme called [Quintom_Ink](https://gitlab.com/Burning_Cube/quintom-cursor-theme) installed in `~/.local/share/icons/` and nwg-look does not recognize this cursor theme.

nwg-look screenshot:

![image](https://github.com/user-attachments/assets/172e7fce-7f44-486f-bf57-7dc377e8e568)

custom-cursor theme install:

![image](https://github.com/user-attachments/assets/07e0e2d5-d751-4cf0-abc5-391c7122db1f)

**Comment by nwg-piotr** [comment]
There are many broken cursor themes over the web. Use another one.
