### ISSUE TITLE
Not all cursor themes listed

### ISSUE THREAD

**Issue by Vladimir-csp** [nwg-piotr/nwg-look#73]
Cursors installed in system:
/usr/share/icons/Adwaita/cursors
/usr/share/icons/DMZ-Black/cursors
/usr/share/icons/DMZ-White/cursors
/usr/share/icons/handhelds/cursors
/usr/share/icons/redglass/cursors
/usr/share/icons/whiteglass/cursors
/usr/share/icons/Obsidian/cursors
/usr/share/icons/Paper/cursors

Cursors listed in nwg-look:
![image](https://github.com/user-attachments/assets/0c7e2aa6-8943-48a6-b3b0-a5b9b14f877f)

**Comment by nwg-piotr** [comment]
Check if what refuses to display contains the `index.theme` file.

**Comment by Vladimir-csp** [comment]
No, only `cursors` subdir.

**Comment by nwg-piotr** [comment]
That's the reason. This file is where the program takes theme names from.
