### ISSUE TITLE
Unable to change icons on void linux

### ISSUE THREAD

**Issue by printfdebugging** [nwg-piotr/nwg-look#77]
Hi, for the last 3 days, I have been trying to change my system icons but I am not able to despite setting it both on the system and the user levels. Recently I noticed a wired warning on the stdout when I ran nwg-look from the terminal.

```
(nwg-look:4388): Gtk-WARNING **: 14:08:06.791: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
WARN[0017] Couldn't create image from '/tmp/nwg-look-cursors/h_double_arrow_000.png' 
INFO[0022] >>> Applying gsettings                       
INFO[0022] >> org.gnome.desktop.interface               
INFO[0022] gtk-theme: Adwaita-dark OK                   
INFO[0022] icon-theme: breeze-dark OK                   
INFO[0022] cursor-theme: Adwaita OK                     
INFO[0022] cursor-size: 24 OK                           
INFO[0022] font-name: Cantarell 11 OK                   
INFO[0022] font-hinting: slight OK                      
INFO[0022] font-antialiasing: grayscale OK              
INFO[0022] font-rgba-order: rgb OK                      
INFO[0022] text-scaling-factor: 1 OK                    
INFO[0022] toolbar-style: both-horiz OK                 
INFO[0022] toolbar-icons-size: large OK                 
INFO[0022] color-scheme: default OK                     
INFO[0022] >> org.gnome.desktop.sound                   
INFO[0022] event-sounds: true OK                        
INFO[0022] input-feedback-sounds: false OK              
INFO[0022] >>> Backing up gsettings to /root/.local/share/nwg-look 
INFO[0022] >>> Exporting /root/.config/gtk-3.0/settings.ini 
INFO[0022] >>> Exporting /root/.gtkrc-2.0               
WARN[0022] Couldn't find icons folder                   
INFO[0022] >>> Exporting /root/.config/xsettingsd/xsettingsd.conf 
```

the icon theme is breeze-dark, and it is on the system in /usr/share/icons, and neofetch also shows it as the system theme, but  the icons are some wierd old school ones.
![image](https://github.com/user-attachments/assets/7ef70d0c-800e-453f-9b70-3335ed3e7202)

Also the icon preview in nwg-look shows some different icons (maybe some fallback) for breeze-dark
![image](https://github.com/user-attachments/assets/f880166f-2f6b-4f58-b86f-30201c8f8f66)

**Comment by nwg-piotr** [comment]
I have no idea what your problem is, but you should not work on the root account for sure.

**Comment by printfdebugging** [comment]
and it's not just with breeze-dark, but with any icon theme. I guess there is some system level package missing, or some setting wrong.

**Comment by nwg-piotr** [comment]
I'm glad you sorted out out.
