### ISSUE TITLE
Doesn't work properly on Hyprland.

### ISSUE THREAD

**Issue by aljustiet** [nwg-piotr/nwg-look#78]
https://github.com/user-attachments/assets/6799fda2-87c7-4e8c-b9e9-ddc678e53ac1

**Comment by nwg-piotr** [comment]
I, and plenty of users, are on Hyprland and the program works well here. Seeing the terminal output would be more instructive.

**Comment by aljustiet** [comment]
> I, and plenty of users, are on Hyprland and the program works well here. Seeing the terminal output would be more instructive.

Maybe the issue is happening because of Hyprland not using wlroots anymore?
<details>
Logs
❯ nwg-look -d
INFO[0000] >>> Loading preferences                      
DEBU[0000] Loaded preferences: {"export-settings-ini":true,"export-gtkrc-20":true,"export-index-theme":true,"export-xsettingsd":true} 
DEBU[0000] lang 'en_US' set from the $LANG variable     
INFO[0000] lang: en_US                                  
INFO[0000] >>> Loading basic lang from '/usr/share/nwg-look/langs/en_US.json' 
DEBU[0000] Cursor theme found: Adwaita                  
DEBU[0000] Cursor theme found: Bibata-Modern-Amber      
DEBU[0000] Cursor theme found: Bibata-Modern-Amber-Right 
DEBU[0000] Cursor theme found: Bibata-Modern-Classic    
DEBU[0000] Cursor theme found: Bibata-Modern-Classic-Right 
DEBU[0000] Cursor theme found: Bibata-Modern-Ice        
DEBU[0000] Cursor theme found: Bibata-Modern-Ice-Right  
DEBU[0000] Cursor theme found: Bibata-Original-Amber    
DEBU[0000] Cursor theme found: Bibata-Original-Amber-Right 
DEBU[0000] Cursor theme found: Bibata-Original-Classic  
DEBU[0000] Cursor theme found: Bibata-Original-Classic-Right 
DEBU[0000] Cursor theme found: Bibata-Original-Ice      
DEBU[0000] Cursor theme found: Bibata-Original-Ice-Right 
INFO[0000] >>> Parsing original /home/aljustiet/.config/gtk-3.0/settings.ini 
WARN[0000] Unsupported config key: gtk-decoration-layout 
WARN[0000] Unsupported config key: gtk-enable-animations 
WARN[0000] Unsupported config key: gtk-modules          
WARN[0000] Unsupported config key: gtk-primary-button-warps-slider 
WARN[0000] Unsupported config key: gtk-sound-theme-name 
WARN[0000] Unsupported config key: gtk-xft-dpi          
DEBU[0000] gtk-theme-name: catppuccin-frappe-sapphire-standard+default 
DEBU[0000] gtk-icon-theme-name: Papirus                 
DEBU[0000] gtk-font-name: GoMono Nerd Font,  12         
DEBU[0000] gtk-cursor-theme-name: Bibata-Modern-Classic 
DEBU[0000] gtk-cursor-theme-size: 32                    
DEBU[0000] gtk-toolbar-style: 3                         
DEBU[0000] gtk-toolbar-icon-size: GTK_ICON_SIZE_LARGE_TOOLBAR 
DEBU[0000] gtk-button-images: false                     
DEBU[0000] gtk-menu-images: false                       
DEBU[0000] gtk-enable-event-sounds: true                
DEBU[0000] gtk-enable-input-feedback-sounds: true       
DEBU[0000] gtk-xft-antialias: 1                         
DEBU[0000] gtk-xft-hinting: 1                           
DEBU[0000] gtk-xft-hintstyle: hintmedium                
DEBU[0000] gtk-xft-rgba: rgb                            
DEBU[0000] gtk-application-prefer-dark-theme: true      
INFO[0000] >>> Reading gsettings                        
INFO[0000] gtk-theme: catppuccin-frappe-sapphire-standard+default 
INFO[0000] icon-theme: Papirus                          
INFO[0000] font-name: GoMono Nerd Font,  12             
INFO[0000] cursor-theme: Bibata-Modern-Classic          
INFO[0000] cursor-size: 32                              
INFO[0000] toolbar-style: both-horiz                    
INFO[0000] toolbar-icons-size: large                    
INFO[0000] font-hinting: medium                         
INFO[0000] font-antialiasing: grayscale                 
INFO[0000] font-rgba-order: rgb                         
INFO[0000] text-scaling-factor: 1                       
INFO[0000] color-scheme: prefer-dark                    
INFO[0000] event-sounds: true                           
INFO[0000] input-feedback-sounds: true                  
DEBU[0000] Theme found: Arc                             
DEBU[0000] Theme found: Arc-Dark                        
DEBU[0000] Theme found: Arc-Darker                      
DEBU[0000] Theme found: Arc-Lighter                     
DEBU[0000] Theme found: Breeze                          
DEBU[0000] Theme found: Breeze-Dark                     
DEBU[0000] Theme found: Colloid-Compact-Gruvbox         
DEBU[0000] Theme found: Colloid-Dark-Compact-Gruvbox    
DEBU[0000] Theme found: Colloid-Dark-Gruvbox            
DEBU[0000] Theme found: Colloid-Green-Compact-Gruvbox   
DEBU[0000] Theme found: Colloid-Green-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Green-Dark-Gruvbox      
DEBU[0000] Theme found: Colloid-Green-Gruvbox           
DEBU[0000] Theme found: Colloid-Green-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Green-Light-Gruvbox     
DEBU[0000] Theme found: Colloid-Grey-Compact-Gruvbox    
DEBU[0000] Theme found: Colloid-Grey-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Grey-Dark-Gruvbox       
DEBU[0000] Theme found: Colloid-Grey-Gruvbox            
DEBU[0000] Theme found: Colloid-Grey-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Grey-Light-Gruvbox      
DEBU[0000] Theme found: Colloid-Gruvbox                 
DEBU[0000] Theme found: Colloid-Light-Compact-Gruvbox   
DEBU[0000] Theme found: Colloid-Light-Gruvbox           
DEBU[0000] Theme found: Colloid-Orange-Compact-Gruvbox  
DEBU[0000] Theme found: Colloid-Orange-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Orange-Dark-Gruvbox     
DEBU[0000] Theme found: Colloid-Orange-Gruvbox          
DEBU[0000] Theme found: Colloid-Orange-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Orange-Light-Gruvbox    
DEBU[0000] Theme found: Colloid-Pink-Compact-Gruvbox    
DEBU[0000] Theme found: Colloid-Pink-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Pink-Dark-Gruvbox       
DEBU[0000] Theme found: Colloid-Pink-Gruvbox            
DEBU[0000] Theme found: Colloid-Pink-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Pink-Light-Gruvbox      
DEBU[0000] Theme found: Colloid-Purple-Compact-Gruvbox  
DEBU[0000] Theme found: Colloid-Purple-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Purple-Dark-Gruvbox     
DEBU[0000] Theme found: Colloid-Purple-Gruvbox          
DEBU[0000] Theme found: Colloid-Purple-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Purple-Light-Gruvbox    
DEBU[0000] Theme found: Colloid-Red-Compact-Gruvbox     
DEBU[0000] Theme found: Colloid-Red-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Red-Dark-Gruvbox        
DEBU[0000] Theme found: Colloid-Red-Gruvbox             
DEBU[0000] Theme found: Colloid-Red-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Red-Light-Gruvbox       
DEBU[0000] Theme found: Colloid-Teal-Compact-Gruvbox    
DEBU[0000] Theme found: Colloid-Teal-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Teal-Dark-Gruvbox       
DEBU[0000] Theme found: Colloid-Teal-Gruvbox            
DEBU[0000] Theme found: Colloid-Teal-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Teal-Light-Gruvbox      
DEBU[0000] Theme found: Colloid-Yellow-Compact-Gruvbox  
DEBU[0000] Theme found: Colloid-Yellow-Dark-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Yellow-Dark-Gruvbox     
DEBU[0000] Theme found: Colloid-Yellow-Gruvbox          
DEBU[0000] Theme found: Colloid-Yellow-Light-Compact-Gruvbox 
DEBU[0000] Theme found: Colloid-Yellow-Light-Gruvbox    
DEBU[0000] Excluded theme: Default                      
DEBU[0000] Excluded theme: Emacs                        
DEBU[0000] Theme found: Gruvbox-Material-Dark           
DEBU[0000] Theme found: Gruvbox-Material-Dark-HIDPI     
DEBU[0000] Theme found: Raleigh                         
DEBU[0000] Theme found: catppuccin-frappe-blue-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-flamingo-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-green-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-lavender-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-maroon-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-mauve-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-peach-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-pink-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-red-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-rosewater-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-sapphire-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-sky-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-teal-standard+default 
DEBU[0000] Theme found: catppuccin-frappe-yellow-standard+default 
INFO[0018] >>> Applying gsettings                       
INFO[0018] >> org.gnome.desktop.interface               
INFO[0018] gtk-theme: catppuccin-frappe-sapphire-standard+default OK 
INFO[0018] icon-theme: Papirus OK                       
INFO[0018] cursor-theme: Bibata-Modern-Classic OK       
INFO[0018] cursor-size: 32 OK                           
INFO[0018] font-name: GoMono Nerd Font,  12 OK          
INFO[0018] font-hinting: medium OK                      
INFO[0018] font-antialiasing: grayscale OK              
INFO[0018] font-rgba-order: rgb OK                      
INFO[0018] text-scaling-factor: 1 OK                    
INFO[0018] toolbar-style: both-horiz OK                 
INFO[0018] toolbar-icons-size: large OK                 
INFO[0018] color-scheme: prefer-dark OK                 
INFO[0018] >> org.gnome.desktop.sound                   
INFO[0018] event-sounds: true OK                        
INFO[0018] input-feedback-sounds: true OK               
INFO[0018] >>> Backing up gsettings to /home/aljustiet/.local/share/nwg-look 
INFO[0018] >>> Exporting /home/aljustiet/.config/gtk-3.0/settings.ini 
DEBU[0018] [Settings]                                   
DEBU[0018] gtk-theme-name=catppuccin-frappe-sapphire-standard+default 
DEBU[0018] gtk-icon-theme-name=Papirus                  
DEBU[0018] gtk-font-name=GoMono Nerd Font,  12          
DEBU[0018] gtk-cursor-theme-name=Bibata-Modern-Classic  
DEBU[0018] gtk-cursor-theme-size=32                     
DEBU[0018] gtk-toolbar-style=3                          
DEBU[0018] gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR 
DEBU[0018] gtk-button-images=0                          
DEBU[0018] gtk-menu-images=0                            
DEBU[0018] gtk-enable-event-sounds=1                    
DEBU[0018] gtk-enable-input-feedback-sounds=1           
DEBU[0018] gtk-xft-antialias=1                          
DEBU[0018] gtk-xft-hinting=1                            
DEBU[0018] gtk-xft-hintstyle=hintmedium                 
DEBU[0018] gtk-xft-rgba=rgb                             
DEBU[0018] gtk-application-prefer-dark-theme=1          
DEBU[0018] gtk-decoration-layout=:minimize,maximize,close 
DEBU[0018] gtk-enable-animations=true                   
DEBU[0018] gtk-modules=colorreload-gtk-module           
DEBU[0018] gtk-primary-button-warps-slider=true         
DEBU[0018] gtk-sound-theme-name=ocean                   
DEBU[0018] gtk-xft-dpi=98304                            
INFO[0018] >>> Exporting /home/aljustiet/.gtkrc-2.0     
DEBU[0018] # DO NOT EDIT! This file will be overwritten by nwg-look. 
DEBU[0018] # Any customization should be done in ~/.gtkrc-2.0.mine instead. 
DEBU[0018]                                              
DEBU[0018] include "/home/aljustiet/.gtkrc-2.0.mine"    
DEBU[0018] gtk-theme-name="catppuccin-frappe-sapphire-standard+default" 
DEBU[0018] gtk-icon-theme-name="Papirus"                
DEBU[0018] gtk-font-name="GoMono Nerd Font,  12"        
DEBU[0018] gtk-cursor-theme-name="Bibata-Modern-Classic" 
DEBU[0018] gtk-cursor-theme-size=32                     
DEBU[0018] gtk-toolbar-style=3                          
DEBU[0018] gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR 
DEBU[0018] gtk-button-images=0                          
DEBU[0018] gtk-menu-images=0                            
DEBU[0018] gtk-enable-event-sounds=1                    
DEBU[0018] gtk-enable-input-feedback-sounds=1           
DEBU[0018] gtk-xft-antialias=1                          
DEBU[0018] gtk-xft-hinting=1                            
DEBU[0018] gtk-xft-hintstyle="hintmedium"               
DEBU[0018] gtk-xft-rgba="rgb"                           
INFO[0018] >>> Exporting /home/aljustiet/.icons/default/index.theme 
INFO[0018] >>> Exporting /home/aljustiet/.config/xsettingsd/xsettingsd.conf 
DEBU[0018] Net/ThemeName "catppuccin-frappe-sapphire-standard+default" 
DEBU[0018] Net/IconThemeName "Papirus"                  
DEBU[0018] Gtk/CursorThemeName "Bibata-Modern-Classic"  
DEBU[0018] Net/EnableEventSounds 1                      
DEBU[0018] EnableInputFeedbackSounds 1                  
DEBU[0018] Xft/Antialias 1                              
DEBU[0018] Xft/Hinting 1                                
DEBU[0018] Xft/HintStyle "hintmedium"                   
DEBU[0018] Xft/RGBA "rgb"
```
</details>

**Comment by aljustiet** [comment]
The issue is that It doesn't preview themes in `nwg-look`

**Comment by aljustiet** [comment]
`GTK_THEME` was set, because of it, nwg-look was obtaining theme from env variable only and not from the gtk settings.
