### ISSUE TITLE
What is the proper way to set the cursor theme?

### ISSUE THREAD

**Issue by manfred3000** [nwg-piotr/nwg-look#9]
OS: Arch Linux
WM: `wlroots`-based
`nwg-look`: 0.1.1

First off, thanks for this great tool, it very much improves the user experience of theming!

Not sure whether this is a bug, but when picking a cursor theme I still have to set the theme manually in `~/.icons/default/index.theme` to make it visible on the plain WM layer/background (on waybar and GUI apps it's working as expected), leaving it blank will make the theme fall back to the "system" cursor.

Any ideas are appreciated,
Thanks again

**Comment by nwg-piotr** [comment]
Somehow I missed it. I will add the editing of this file to the program.
